# Generated by Django 3.1 on 2020-08-29 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0002_auto_20200829_1930'),
        ('documentos', '0002_documento_colaborador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='colaborador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='colaboradores.colaborador'),
            preserve_default=False,
        ),
    ]
