# Generated by Django 3.1 on 2020-08-30 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('colaboradores', '0003_auto_20200830_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='empresas.empresa'),
        ),
    ]
